name: CI/CD deploy master

on:
  push:
    branches: ["master"]

jobs:
  deploy_master:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19' # Specify the minimum required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular, output in dist/mycv
        run: CI=false npm run build

      - name: Show directory contents
        run: ls -la dist/mycv/browser

      - name: Download & run httpd image
        run: docker run -d --name serving_base httpd

      - name: List running Docker containers
        run: docker ps

      - name: Copy Angular build to container
        run: docker cp dist/mycv/browser/. serving_base:/usr/local/apache2/htdocs

      - name: List container contents
        run: docker exec serving_base ls -la /usr/local/apache2/htdocs
